---
- name: Install collectd
  package:
    name: collectd
    state: "{{ (collectd_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: collectd restart

- name: Remove legacy collectd config files
  file:
    path: "{{ item }}"
    state: absent
  with-items:
    - /etc/collectd.conf
    - /etc/collect.d
  when: _install_package.changed
  